#lang racket

(require "parser.rkt")
(require "itemizer.rkt")
(require "x86.rkt")

; Now: let's start with a basic parse tree.
(define fib-example '(fib ((n u4)) u4
                          (if (<= n 1)
                              1
                              (+ (fib (- n 1))
                                 (fib (- n 2))))))
(define ack-example '(ack ((m u4) (n u4)) u4
                          (if (== m 0)
                              (+ n 1)
                              (if (== n 0)
                                  (ack (- m 1) 1)
                                  (ack (- m 1) (ack m (- n 1)))))))
(define math-example '(math ((a u4) (b u4)) u4
                             (+ a b)))
(define example fib-example)

; OLD: Let's start with a simple tree that we'll get from the parser/front-end generator.
(define sample-old '(fib (u4) u4
                     ((branch (<= (arg 0) (const 1 u4)) 1 2))
                     ((return (const 1 u4)))
                     ((return (+ (call fib (- (arg 0) (const 1 u4)))
                                 (call fib (- (arg 0) (const 2 u4))))))))

; Not currently used.
(define reduced-old '(fib (u4) u4
                      ((swr 0 (arg 0))
                       (swr 1 (<= (swr 0) (const 1 u4)))
                       (branch (swr 1) 1 2))
                      ((swr 0 (const 1 u4))
                       (return (swr 0)))
                      ((swr 0 (arg 0))
                       (swr 2 (- (swr 0) (const 1 u4)))
                       (swr 3 (call fib (swr 2)))
                       (swr 5 (- (swr 0) (const 2 u4)))
                       (swr 6 (call fib (swr 5)))
                       (swr 7 (+ (swr 3) (swr 6)))
                       (return (swr 7)))))

; Not currently used.
(define x86-simple-near '(fib (u4) u4
                              ((mov eax (mem esp 4))
                               (cmp eax (dword 1))
                               (jle 1)
                               (jmp 2))
                              ((mov eax (dword 1))
                               (ret))
                              ((mov eax (mem esp 4))
                               (sub eax (dword 1))
                               (push eax)
                               (call fib)
                               (add esp 4)
                               (mov ecx (mem esp 4))
                               (sub ecx (dword 1))
                               (push eax)
                               (push ecx)
                               (call fib)
                               (add esp 4)
                               (pop ecx)
                               (add eax ecx)
                               (ret))))

example
(define sample (parse example))
sample
(define reduced (itemize sample))
reduced
(define allocd (x86-register-allocation reduced))
allocd
(define medium (cdr (x86-transform allocd)))
medium
(define flat (x86-asm-flatten medium))
flat
(define mitigated (x86-asm-add-mitigation (car allocd) flat))
mitigated
(define textual (x86-asm-write-flat mitigated))
(display textual)
(newline)
(display-to-file (string-append "; Generated by SACK.\n" textual "\n") "test.s" #:mode 'text #:exists 'replace)
